angeline/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path
from django.contrib.auth.views import LoginView
from .views import cadastro, CustomLoginView, home, host, perfil, CustomLogoutView, editar_perfil, editar_host, perfil_host, evento, specific_page, host_servico, agendar_evento, editar_evento, cancelar, excluir_evento, completar_perfil, criar_host, lista_reservas, gerenciamento, cardapio

app_name = 'angeline'

urlpatterns = [
    path('cadastro', cadastro, name='cadastro'),
    path('login', CustomLoginView.as_view(), name='login'),
    path('home', home, name='home'),
    path('seja host', host, name='host'),
    path('perfil', perfil, name='perfil'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('editar_perfil', editar_perfil, name='editar_perfil'),
    path('editar_host', editar_host, name='editar_host'),
    path('perfil_host', perfil_host, name='perfil_host'),
    path('evento', evento, name='evento'),
    path('specific_page/<int:evento_id>/', specific_page, name='specific_page'),
    path('host_servico/<int:evento_id>/', host_servico, name='host_servico'),
    path('evento/<int:evento_id>/', agendar_evento, name='agendar_evento'),
    path('reservas/', lista_reservas, name='lista_reservas'),
    path('editar_evento/<int:evento_id>/', editar_evento, name='editar_evento'),
    path('cancelar/<int:agendamento_id>/cancelar/', cancelar, name='cancelar'),
    path('excluir_evento/<int:evento_id>/', excluir_evento, name='excluir_evento'),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('criar_host', criar_host, name='criar_host'),
    path('completar_perfil', completar_perfil, name='completar_perfil'),
    path('cardapio', cardapio, name='cardapio'),
    path('gerenciamento', gerenciamento, name='gerenciamento'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import home_page
app_name = 'main'

urlpatterns = [
    path('', home_page, name='home_page')
]

myfood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('',include('angeline.urls', namespace='angeline')),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

angeline/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth import logout, authenticate, login as auth_login
from django.contrib import messages
from .models import CompleteCadastro,Host, Evento, Reserva
from .forms import CustomUserCreationForm, CustomUserLoginForm, CompleteCadastroForm, HostForm, EventoForm, AgendamentoForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.views import View


def cadastro(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Cadastro realizado com sucesso. Faça o login.')
            return redirect('angeline:login')
        else:
            messages.error(request, 'Erro no cadastro. Por favor, corrija os erros abaixo.')
    else:
        form = CustomUserCreationForm()

    return render(request, 'register/cadastro.html', {'form': form})


class CustomLoginView(LoginView):
    template_name = 'register/login.html'
    authentication_form = CustomUserLoginForm


class CustomLogoutView(LogoutView):
    next_page = 'main:base'


@login_required
def home(request):
    perfil_usuario = CompleteCadastro.objects.filter(usuario=request.user).first()
    eventos = Evento.objects.all()

    if perfil_usuario: 
        if perfil_usuario.is_complete():  
            return render(request, 'angeline/home.html', {'eventos': eventos,'perfil_usuario': perfil_usuario, 'form_preenchido': True})
        else:
            return render(request, 'angeline/home.html', {'eventos': eventos,'form_preenchido': False})
    else:
        return render(request, 'angeline/home.html', {'eventos': eventos,'form_preenchido': False})


    


@login_required
def host(request):
    user = request.user

    if Host.objects.filter(usuario=user).exists():
        return redirect('angeline:perfil_host')
    else:
        return redirect('angeline:editar_host')
    
    
@login_required
def perfil(request):
    perfil_usuario = CompleteCadastro.objects.filter(usuario=request.user).first()

    try:
        host = request.user.host
    except Host.DoesNotExist:
        host = None

    created = False

    if 'edit' in request.GET:
        return redirect('angeline:editar_perfil')

    if request.method == 'POST':
        form = CompleteCadastroForm(request.POST, request.FILES, instance=perfil_usuario)
        if form.is_valid():
            if not perfil_usuario:
                perfil_usuario = form.save(commit=False)
                perfil_usuario.usuario = request.user
                perfil_usuario.save()
                created = True
            else:
                form.save()

            return redirect('angeline:perfil')
    else:
        form = CompleteCadastroForm(instance=perfil_usuario)

    user_email = request.user.email if request.user else None

    return render(request, 'angeline/perfil.html', {'form': form, 'perfil_usuario': perfil_usuario, 'host': host, 'form_preenchido': not created, 'user_email': user_email})



def completar_perfil(request):
    if request.method == 'POST':
        form = CompleteCadastroForm(request.POST, request.FILES)
        if form.is_valid():
            perfil = form.save(commit=False)
            perfil.usuario = request.user  
            perfil.save()
            return redirect('angeline:perfil')
    else:
        form = CompleteCadastroForm()
    
    return render(request, 'angeline/completar_perfil.html', {'form': form})




@login_required
def editar_perfil(request):
    perfil_usuario, created = CompleteCadastro.objects.get_or_create(usuario=request.user)

    if request.method == 'POST':
        form = CompleteCadastroForm(request.POST, request.FILES, instance=perfil_usuario)
        if form.is_valid():
            form.save()
            return redirect('angeline:perfil')  
    else:
        form = CompleteCadastroForm(instance=perfil_usuario)

    return render(request, 'angeline/editar_perfil.html', {'form': form, 'perfil_usuario': perfil_usuario})


@login_required
def evento(request):
    perfil_usuario, created = CompleteCadastro.objects.get_or_create(usuario=request.user)

    if request.method == 'POST':
        form = EventoForm(request.POST, request.FILES) 
        if form.is_valid():
            evento = form.save(commit=False)
            evento.host, created = Host.objects.get_or_create(usuario=request.user, defaults={'nome_empresa': 'Nome da Empresa Padrão'})
            evento.save()  
            form.save_m2m()  
            messages.success(request, 'Evento criado com sucesso!')
            return redirect('angeline:home') 
    else:
        form = EventoForm()

    eventos = Evento.objects.all()

    return render(request, 'angeline/evento.html', {'form': form, 'perfil_usuario': perfil_usuario, 'eventos': eventos})




def specific_page(request, evento_id):
    evento = get_object_or_404(Evento, id=evento_id)

    context = {
        'evento': evento,
    }

    return render(request, 'angeline/specific_page.html', context)


def criar_host(request):
    if request.method == 'POST':
        form = HostForm(request.POST)
        if form.is_valid():
            host = form.save(commit=False)
            host.usuario = request.user
            host.save()
            return redirect('angeline:perfil')
    else:
        form = HostForm()
    return render(request, 'angeline/criar_host.html', {'form': form})


@login_required
def editar_host(request):
    host, created = Host.objects.get_or_create(usuario=request.user)
    if request.method == 'POST':
        form = HostForm(request.POST, request.FILES, instance=host)
        if form.is_valid():
            form.save()
            messages.success(request, 'Informações do host atualizadas com sucesso!')
            return redirect('angeline:host')  
    else:
        form = HostForm(instance=host)
    return render(request, 'angeline/editar_host.html', {'form': form, 'host': host, 'form_preenchido': not created})


@login_required
def perfil_host(request):
    host, created = Host.objects.get_or_create(usuario=request.user)

    if 'edit' in request.GET:
        return redirect('angeline:editar_host')

    if request.method == 'POST':
        form = HostForm(request.POST, request.FILES, instance=host)
        if form.is_valid():
            form.save()

            if created:
                return redirect('angeline:perfil_host')
    else:
        form = HostForm(instance=host)

    return render(request, 'angeline/host.html', {'form': form, 'host': host, 'form_preenchido': not created})


def host_servico(request, evento_id):
    evento = get_object_or_404(Evento, id=evento_id)
    
    context = {
        'evento': evento,
    }
    
    return render(request, 'angeline/host_servico.html', context)
    

@login_required
def editar_evento(request, evento_id):
    evento = get_object_or_404(Evento, id=evento_id)

    if request.user != evento.host.usuario:
        return redirect('angeline:home')

    if request.method == 'POST':
        form = EventoForm(request.POST, request.FILES, instance=evento)
        if form.is_valid():
            form.save()
            return redirect('angeline:specific_page', evento_id=evento.id)
    else:
        form = EventoForm(instance=evento)

    return render(request, 'angeline/editar_evento.html', {'form': form, 'evento': evento})



@login_required
def agendar_evento(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    
    if request.method == 'POST':
        form = AgendamentoForm(request.POST)
        
        if form.is_valid():
            reserva = form.save(commit=False)
            reserva.usuario = request.user
            reserva.evento = evento
            reserva.save()
            
            return redirect('angeline:lista_reservas')
    else:
        form = AgendamentoForm()
    
    return render(request, 'angeline/agendar_evento.html', {'form': form, 'evento': evento})

@login_required
def lista_reservas(request):
    reservas = Reserva.objects.filter(usuario=request.user)
    return render(request, 'angeline/lista_reservas.html', {'reservas': reservas})


@login_required
def cancelar(request, agendamento_id):
    reserva = get_object_or_404(Reserva, id=agendamento_id, usuario=request.user)
    evento = reserva.evento
    reserva.delete()
    
    return redirect('angeline:lista_reservas')


@login_required
def excluir_evento(request, evento_id):
    evento = get_object_or_404(Evento, id=evento_id, host__usuario=request.user)
    evento.delete() 
    return redirect('angeline:home')



def cardapio(request):
    return render(request, 'angeline/cardapio.html')
    return redirect('angeline:gerenciamento')


@login_required
def gerenciamento(request):
    eventos = Evento.objects.filter(host=request.user.host)
    return render(request, 'angeline/gerenciamento.html', {'eventos': eventos})

angeline/templates/register/cadastro.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'angeline/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'angeline/style_form.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Outfit' rel='stylesheet'>
</head>

<body>
        

    <img class="box_shadow_img" src="static/img/img_cadastro.jpg" />
    <div class="box_shadow_img2"></div>
    <div class="faça_seu_cadastro">
        <span class="span_faca_seu">Faça seu </span>
        <span class="span_cad">Cadastro</span>
        <span class="span_e">!</span>
    </div>
    <div class="quadrado_roxo"></div>
    <div class="container">
        <form method="post" action="{% url 'angeline:cadastro' %}">
            {% csrf_token %}
    
            {{ form.as_p }}
    
            <button type="submit">Cadastre-se</button>
            <h6>Já tem uma conta? Faça seu login <a href="{% url 'angeline:login' %}">aqui</a></h6>
        </form>
    </div>
    
    <div class="textos">
        <span class="span_descubra">“Descubra a arte da boa comida através de uma </span>
        <span class="span_exp-exc" style="color: #F1C400;">experiência exclusiva</span>
        <span class="span_mergulhe">. Cadastre-se e mergulhe em sabores memoráveis.”</span>
    </div>
    <!-- <div class="container">
        <h2>Cadastro</h2>
        <form method="post" action="{% url 'angeline:cadastro' %}">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Cadastrar</button>
            <h6>Já tem uma conta? Faça seu login <a href="{% url 'angeline:login' %}">aqui</a></h6>
        </form>
    </div>  -->

</body>

</html>

angeline/templates/register/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>flavorxp</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'angeline/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'angeline/login.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Outfit' rel='stylesheet'>
</head>

<body>

    <div class="container">
        <h2>FlavorXP</h2>
        <h3>Fazer login</h3>
        <form method="post" action="{% url 'angeline:login' %}">
            {% csrf_token %}
            
            <div class="formulario">            
                {{ form.as_p }}
            </div>

            <button type="submit">Entrar</button>
           
            <a href="{% url 'angeline:password_reset' %}">Esqueceu a senha?</a>

            <h6>Ainda não tem uma conta? Cadastre-se <a href="{% url 'angeline:cadastro' %}">aqui</a></h6>

            {% if error_message %}
                <p class="error">{{ error_message }}</p>
            {% endif %}
        </form>
    </div>

</body>

</html>

angeline/templates/register/password_reset_form.html
<h2>Redefinir Senha</h2>
  <form method="post" action="{% url 'password_reset' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar E-mail de Redefinição de Senha</button>
  </form>