angeline/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path
from django.contrib.auth.views import LoginView
from .views import cadastro, CustomLoginView, home, host, perfil, CustomLogoutView, editar_perfil, editar_host, perfil_host, evento, specific_page, host_servico, agendar_evento, editar_evento, cancelar, excluir_evento, completar_perfil, criar_host, lista_reservas, gerenciamento, cardapio

app_name = 'angeline'

urlpatterns = [
    path('cadastro', cadastro, name='cadastro'),
    path('login', CustomLoginView.as_view(), name='login'),
    path('home', home, name='home'),
    path('seja host', host, name='host'),
    path('perfil', perfil, name='perfil'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('editar_perfil', editar_perfil, name='editar_perfil'),
    path('editar_host', editar_host, name='editar_host'),
    path('perfil_host', perfil_host, name='perfil_host'),
    path('evento', evento, name='evento'),
    path('specific_page/<int:evento_id>/', specific_page, name='specific_page'),
    path('host_servico/<int:evento_id>/', host_servico, name='host_servico'),
    path('evento/<int:evento_id>/', agendar_evento, name='agendar_evento'),
    path('reservas/', lista_reservas, name='lista_reservas'),
    path('editar_evento/<int:evento_id>/', editar_evento, name='editar_evento'),
    path('cancelar/<int:agendamento_id>/cancelar/', cancelar, name='cancelar'),
    path('excluir_evento/<int:evento_id>/', excluir_evento, name='excluir_evento'),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('criar_host', criar_host, name='criar_host'),
    path('completar_perfil', completar_perfil, name='completar_perfil'),
    path('cardapio', cardapio, name='cardapio'),
    path('gerenciamento', gerenciamento, name='gerenciamento'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import home_page
app_name = 'main'

urlpatterns = [
    path('', home_page, name='home_page')
]

myfood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('',include('angeline.urls', namespace='angeline')),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

angeline/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth import logout, authenticate, login as auth_login
from django.contrib import messages
from .models import CompleteCadastro,Host, Evento, Reserva
from .forms import CustomUserCreationForm, CustomUserLoginForm, CompleteCadastroForm, HostForm, EventoForm, AgendamentoForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.views import View


def cadastro(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Cadastro realizado com sucesso. Faça o login.')
            return redirect('angeline:login')
        else:
            messages.error(request, 'Erro no cadastro. Por favor, corrija os erros abaixo.')
    else:
        form = CustomUserCreationForm()

    return render(request, 'register/cadastro.html', {'form': form})


class CustomLoginView(LoginView):
    template_name = 'register/login.html'
    authentication_form = CustomUserLoginForm


class CustomLogoutView(LogoutView):
    next_page = 'main:base'


@login_required
def home(request):
    perfil_usuario = CompleteCadastro.objects.filter(usuario=request.user).first()
    eventos = Evento.objects.all()

    if perfil_usuario: 
        if perfil_usuario.is_complete():  
            return render(request, 'angeline/home.html', {'eventos': eventos,'perfil_usuario': perfil_usuario, 'form_preenchido': True})
        else:
            return render(request, 'angeline/home.html', {'eventos': eventos,'form_preenchido': False})
    else:
        return render(request, 'angeline/home.html', {'eventos': eventos,'form_preenchido': False})


    


@login_required
def host(request):
    user = request.user

    if Host.objects.filter(usuario=user).exists():
        return redirect('angeline:perfil_host')
    else:
        return redirect('angeline:editar_host')
    
    
@login_required
def perfil(request):
    perfil_usuario = CompleteCadastro.objects.filter(usuario=request.user).first()

    try:
        host = request.user.host
    except Host.DoesNotExist:
        host = None

    created = False

    if 'edit' in request.GET:
        return redirect('angeline:editar_perfil')

    if request.method == 'POST':
        form = CompleteCadastroForm(request.POST, request.FILES, instance=perfil_usuario)
        if form.is_valid():
            if not perfil_usuario:
                perfil_usuario = form.save(commit=False)
                perfil_usuario.usuario = request.user
                perfil_usuario.save()
                created = True
            else:
                form.save()

            return redirect('angeline:perfil')
    else:
        form = CompleteCadastroForm(instance=perfil_usuario)

    user_email = request.user.email if request.user else None

    return render(request, 'angeline/perfil.html', {'form': form, 'perfil_usuario': perfil_usuario, 'host': host, 'form_preenchido': not created, 'user_email': user_email})



def completar_perfil(request):
    if request.method == 'POST':
        form = CompleteCadastroForm(request.POST, request.FILES)
        if form.is_valid():
            perfil = form.save(commit=False)
            perfil.usuario = request.user  
            perfil.save()
            return redirect('angeline:perfil')
    else:
        form = CompleteCadastroForm()
    
    return render(request, 'angeline/completar_perfil.html', {'form': form})




@login_required
def editar_perfil(request):
    perfil_usuario, created = CompleteCadastro.objects.get_or_create(usuario=request.user)

    if request.method == 'POST':
        form = CompleteCadastroForm(request.POST, request.FILES, instance=perfil_usuario)
        if form.is_valid():
            form.save()
            return redirect('angeline:perfil')  
    else:
        form = CompleteCadastroForm(instance=perfil_usuario)

    return render(request, 'angeline/editar_perfil.html', {'form': form, 'perfil_usuario': perfil_usuario})


@login_required
def evento(request):
    perfil_usuario, created = CompleteCadastro.objects.get_or_create(usuario=request.user)

    if request.method == 'POST':
        form = EventoForm(request.POST, request.FILES) 
        if form.is_valid():
            evento = form.save(commit=False)
            evento.host, created = Host.objects.get_or_create(usuario=request.user, defaults={'nome_empresa': 'Nome da Empresa Padrão'})
            evento.save()  
            form.save_m2m()  
            messages.success(request, 'Evento criado com sucesso!')
            return redirect('angeline:home') 
    else:
        form = EventoForm()

    eventos = Evento.objects.all()

    return render(request, 'angeline/evento.html', {'form': form, 'perfil_usuario': perfil_usuario, 'eventos': eventos})




def specific_page(request, evento_id):
    evento = get_object_or_404(Evento, id=evento_id)

    context = {
        'evento': evento,
    }

    return render(request, 'angeline/specific_page.html', context)


def criar_host(request):
    if request.method == 'POST':
        form = HostForm(request.POST)
        if form.is_valid():
            host = form.save(commit=False)
            host.usuario = request.user
            host.save()
            return redirect('angeline:perfil')
    else:
        form = HostForm()
    return render(request, 'angeline/criar_host.html', {'form': form})


@login_required
def editar_host(request):
    host, created = Host.objects.get_or_create(usuario=request.user)
    if request.method == 'POST':
        form = HostForm(request.POST, request.FILES, instance=host)
        if form.is_valid():
            form.save()
            messages.success(request, 'Informações do host atualizadas com sucesso!')
            return redirect('angeline:host')  
    else:
        form = HostForm(instance=host)
    return render(request, 'angeline/editar_host.html', {'form': form, 'host': host, 'form_preenchido': not created})


@login_required
def perfil_host(request):
    host, created = Host.objects.get_or_create(usuario=request.user)

    if 'edit' in request.GET:
        return redirect('angeline:editar_host')

    if request.method == 'POST':
        form = HostForm(request.POST, request.FILES, instance=host)
        if form.is_valid():
            form.save()

            if created:
                return redirect('angeline:perfil_host')
    else:
        form = HostForm(instance=host)

    return render(request, 'angeline/host.html', {'form': form, 'host': host, 'form_preenchido': not created})


def host_servico(request, evento_id):
    evento = get_object_or_404(Evento, id=evento_id)
    
    context = {
        'evento': evento,
    }
    
    return render(request, 'angeline/host_servico.html', context)
    

@login_required
def editar_evento(request, evento_id):
    evento = get_object_or_404(Evento, id=evento_id)

    if request.user != evento.host.usuario:
        return redirect('angeline:home')

    if request.method == 'POST':
        form = EventoForm(request.POST, request.FILES, instance=evento)
        if form.is_valid():
            form.save()
            return redirect('angeline:specific_page', evento_id=evento.id)
    else:
        form = EventoForm(instance=evento)

    return render(request, 'angeline/editar_evento.html', {'form': form, 'evento': evento})



@login_required
def agendar_evento(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    
    if request.method == 'POST':
        form = AgendamentoForm(request.POST)
        
        if form.is_valid():
            reserva = form.save(commit=False)
            reserva.usuario = request.user
            reserva.evento = evento
            reserva.save()
            
            return redirect('angeline:lista_reservas')
    else:
        form = AgendamentoForm()
    
    return render(request, 'angeline/agendar_evento.html', {'form': form, 'evento': evento})

@login_required
def lista_reservas(request):
    reservas = Reserva.objects.filter(usuario=request.user)
    return render(request, 'angeline/lista_reservas.html', {'reservas': reservas})


@login_required
def cancelar(request, agendamento_id):
    reserva = get_object_or_404(Reserva, id=agendamento_id, usuario=request.user)
    evento = reserva.evento
    reserva.delete()
    
    return redirect('angeline:lista_reservas')


@login_required
def excluir_evento(request, evento_id):
    evento = get_object_or_404(Evento, id=evento_id, host__usuario=request.user)
    evento.delete() 
    return redirect('angeline:home')



def cardapio(request):
    return render(request, 'angeline/cardapio.html')
    return redirect('angeline:gerenciamento')


@login_required
def gerenciamento(request):
    eventos = Evento.objects.filter(host=request.user.host)
    return render(request, 'angeline/gerenciamento.html', {'eventos': eventos})

angeline/templates/angeline/agendamento.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{% static 'angeline/bootstrap.css' %}">

    <title>Agendamento</title>
</head>
<body>
    <h1>Agendar Evento: {{ evento.tema }}</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Agendar</button>
    </form>
    <a href="{% url 'angeline:specific_page' evento_id=evento.id %}">Voltar</a>
</body>
</html>

angeline/templates/angeline/agendar_evento.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{% static 'angeline/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'angeline/agendar.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Outfit' rel='stylesheet'>

    <title>Agendamento</title>
</head>
<body>
    <div class="container">
        <h2 class="titulo">Agendar Evento: {{ evento.tema }}</h2>

        <form action="" method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value=" Agendar " class="butao">
        </form>

        <div class="voltar"><a href="{% url 'angeline:specific_page' evento_id=evento.id %}">Voltar</a></div> 

    </div>

    

    <
</body>
</html>

angeline/templates/angeline/cardapio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{% static 'angeline/cardapio.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Outfit' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <div class="container">
        <h1 class="titulo">Cardápio do Dia</h1>
        <div class="cardapio">
            <div class="item">
                <h2>Prato Principal</h2>
                <p>Massas ao molho branco e especiarias</p>
            </div>
            <div class="item">
                <h2>Acompanhamento</h2>
                <p>saladas e petiscos</p>
            </div>
            <div class="item">
                <h2>Sobremesa</h2>
                <p>Pudim de leite condensado</p>
            </div>
        </div>

        <div class="observacao">
            <h3>Observações:</h3>
            <p>Este cardápio está sujeito a alterações sem aviso prévio. Consulte nosso pessoal para informações atualizadas.</p>
        </div>
    </div>
</body>

</html>
</html>

angeline/templates/angeline/completar_perfil.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Complete Seu Perfil</title>
    <link rel="stylesheet" href="{% static 'angeline/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'angeline/completa.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Outfit' rel='stylesheet'>
</head>

<body>
    <div class="container">
        <h1>Complete Seu Perfil</h1>
        <form method="post" action="{% url 'angeline:completar_perfil' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Salvar</button>
        </form>
        <a href="{% url 'angeline:home' %}">Voltar para Home</a>
    </div>
    <script src="{% static 'angeline/perfil.js' %}"></script>
</body>

</html>

angeline/templates/angeline/criar_host.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'angeline/editar_host.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Outfit' rel='stylesheet'>
    <title>Document</title>
</head>

<body>
    <div class="container">
        <h1>Criar Host</h1>
        <form method="post" action="{% url 'angeline:criar_host' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Salvar</button>
        </form>
    </div>
</body>

</html>

angeline/templates/angeline/editar_host.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Host</title>
    <link rel="stylesheet" href="{% static 'angeline/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'angeline/editar_host.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Outfit' rel='stylesheet'>
</head>

<body>
    <div class="container">
        <h1>Editar Host</h1>
        <form method="post" action="{% url 'angeline:editar_host' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
        
            <button type="submit">Salvar</button>
        </form>
        
    </div>
</body>


</html>

angeline/templates/angeline/editar_perfil.html
<!-- angeline/templates/angeline/editar_perfil.html -->

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Perfil</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'angeline/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'angeline/editar_perfil.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Outfit' rel='stylesheet'>
</head>

<body>
    <div class="container">

        <h1>Editar Perfil</h1>

        <form method="post" action="{% url 'angeline:editar_perfil' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Salvar</button>
        </form>
        <body>
        
            
            <script>
                document.addEventListener("DOMContentLoaded", function () {
                    
                    const clearCheckbox = document.getElementById("foto-clear_id");
                    const fotoInput = document.getElementById("id_foto");
        
                    
                    clearCheckbox.addEventListener("change", function () {
                        
                        if (clearCheckbox.checked) {
                           
                            fotoInput.value = "";
                        }
                    });
                });
            </script>

    </div>
</body>

</html>

angeline/templates/angeline/evento.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{% static 'angeline/bootstrap.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Outfit' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'angeline/criar_evento.css' %}">

</head>
<body>

  
<div class="container"> 
  <h1>Crie um evento!</h1>
 
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar evento</button>
  </form>
</div>
</body>
</html>

angeline/templates/angeline/filtrar_cidades.html
<!DOCTYPE html>
<html>
<head>
    <title>Filtro de Cidades</title>
</head>
<body>
    <form method="post" action="{% url 'angeline:filtrar_cidades' %}">
        {% csrf_token %}
        <label for="filtro">Digite o termo:</label>
        <input type="text" name="filtro" required>
        <button type="submit">Filtrar</button>
    </form>
</body>
</html>

angeline/templates/angeline/lista_reservas.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{% static 'angeline/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'angeline/agendar.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Outfit' rel='stylesheet'>
    <title>Agendamentos</title>
</head>
<body>

    <div class="container">
        <h2 class="titulo">Suas Reservas</h2>

        {% for reserva in reservas %}
        <p>Evento: {{ reserva.evento.tema }} - Pessoas: {{ reserva.quantidade_pessoas }} - Nomes: {{ reserva.nomes_pessoas }}</p>
        <form action="{% url 'angeline:cancelar' reserva.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="butao">Cancelar</button>
        </form>
        {% empty %}
        <p>Você não tem nenhuma reserva.</p>
        {% endfor %}



        <a class="voltar" href="{% url 'angeline:perfil' %}">Voltar</a>
    </div>

</body>
</html>

angeline/templates/angeline/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'angeline/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'angeline/base.css' %}">
</head>

<body>

    <div class="container">
        <h2>Login</h2>
        <form method="post" action="{% url 'angeline:login' %}">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Entrar</button>
            <h6>Não tem uma conta? <a href="{% url 'angeline:cadastro' %}">Cadastre-se </a></h6>
        </form>
    </div>

</body>

</html>

angeline/templates/angeline/specific_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{% static 'angeline/specific_page.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Outfit' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>Document</title>
</head>

<body>
        <img class="imagem_evento" src="{{ evento.fotos.url }}" />
        <div class="gradiente_imagem"></div>
        <div class="nome_do_evento">{{ evento.tema }}</div>
        <div class="estilo_da_experiencia">Estilo da experiência:</div>
        <div class="quadrado_conteudo1">
            <div class="jantar">{{ evento.estilo }}</div>
        </div>
        <div class="nome_da_marca_oferece">
        <a class="link_nome_host" href="{% url 'angeline:host_servico' evento_id=evento.id %}"><span class="nome_da_marca">{{ evento.host }} </span></a>
        <span class="oferece">oferece:</span>
        </div>
        <div class="barra1"></div>
        <div class="barra2"></div>
        <div style="width: 590px; margin-top: 1560px; margin-left:120px"><span style="color: black; font-size: 24px; font-family: Outfit; font-weight: 700; word-wrap: break-word">Descrição: </span><span style="color: black; font-size: 24px; font-family: Outfit; font-weight: 200; word-wrap: break-word">{{ evento.descricao }}</span></div>
        <div class="barra3"></div>
        <i class="fa-solid fa-utensils"></i>
        <div class="cardapio">Cardápio</div>
        <a href="{% url 'angeline:cardapio' %}"><div class="quadrado_conteudo_roxo"></div></a>
        <div class="convidados1">Convidados:</div>
        <div class="quadrado_conteudo2"></div>
        <div class="convidados">Convidados</div>
        <div class="numero_convidados">{{ evento.max_convidados }}</div>
        <div class="incluso_restricao">Incluso para restrição:</div>
        <div class="quadrado_conteudo3"></div>
        <i class="fa-solid fa-circle-exclamation"></i>
        <div class="tipo_restricao">{{ evento.restricao }}</div>
        <div class="data_e_horario">Data e Horário:</div>
        <div class="quadrado_conteudo4"></div>
        <div class="data">{{ evento.data }}</div>
        <div class="as">às</div>
        <div class="horario">{{ evento.horario }}h</div>
        <i class="fa-solid fa-book"></i>
        <div class="acesse">Acesse</div>
        <div class="bebidas_oferecidas">Bebidas oferecidas:</div>
        <div class="quadrado_conteudo_roxo2"></div>
        <i class="fa-solid fa-wine-bottle"></i>
        <div class="acesse2">Acesse</div>

        <div class="localizacao">Localização</div>
        <div class="sombra"></div>
        <div class="descricao_do_evento_no_card_de_pagamento">Jantar para {{ evento.max_convidados }} convidados  no dia {{ evento.data }} às {{ evento.horario }}h</div>
        <div class="mapa-container"> <!-- Container do mapa -->
            <iframe class="mapa" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3557.5251179439297!2d-49.07062772456039!3d-26.918562376643766!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94df18c164923a89%3A0x3d323de3e517175c!2sTeatro%20Carlos%20Gomes!5e0!3m2!1spt-BR!2sbr!4v1709212434023!5m2!1spt-BR!2sbr" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
          </div>
        <div class="retangulo_degrade_pgto"></div>
        <div class="valor_da_experiencia">Valor da experiência</div>
        <div class="preco">R${{ evento.valor_host }}</div>
        <div class="botão_agendar"></div>
        <div class="texto_agendar_pgto"><a href="{% url 'angeline:agendar_evento' evento_id=evento.id %}">Agendar</a></div>

        <script src="https://maps.googleapis.com/maps/api/js?key=SUA_CHAVE_DA_API&callback=initMap" async defer></script>

        

</body>

</html>